version: '3.0'
services:
  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - app_network
    command: server /data --console-address ":9001"
    restart: unless-stopped

  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=servidor_database
    ports:
      - '5434:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    restart: unless-stopped

  servidor-api:
    container_name: servidor-api
    image: servidor-api-image:latest
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - minio
    networks:
      - app_network
    environment:
      - JDBC_URL=jdbc:postgresql://postgres:5432/servidor_database
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=root
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_HOST=http://127.0.0.1
      - MINIO_PORT=9000
      - MINIO_EXPIRACAO=5M
      - CORS_ORIGINS=http://localhost:8080
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  minio_data:
    driver: local
