version: '3.0'
services:
  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    network_mode: "host"
    command: server --address 0.0.0.0:9000 /data
    restart: unless-stopped

  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=servidor_database
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: "host"
    restart: unless-stopped

  servidor-api:
    container_name: servidor-api
    image: quarkus/controle-servidor-api-jvm:latest
    depends_on:
      - postgres
      - minio
    network_mode: "host"
    environment:
      - JDBC_URL=jdbc:postgresql://localhost:5432/servidor_database
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=root
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_HOST=localhost
      - MINIO_PORT=9000
      - MINIO_EXPIRACAO=5M
      - CORS_ORIGINS=http://localhost:8080
    restart: unless-stopped

volumes:
  minio_data:
    driver: local
