version: '3.0'
services:
  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_ACCESS_KEY=minioaccesskey
      - MINIO_SECRET_KEY=miniosecretkey
    networks:
      - app_network
    command: server /data --console-address ":9001"
    restart: unless-stopped

  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: servidor_database
    ports:
      - '5434:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    restart: unless-stopped

#  servidor-api:
#    container_name: servidor-api
#    image: servidor-api-image:latest
#    ports:
#      - '8080:8080'
#    depends_on:
#      - postgres
#      - minio
#    networks:
#      - app_network
#    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  minio_data:
    driver: local
